Add test reporting to CI/CD

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,10 +54,14 @@ jobs:
         run: pnpm lint
         # run all of Build/Lint/Test even if earlier steps fail so we have "all results" at our disposal.
         if: ${{ (success() || failure()) && steps.pnpm-install.conclusion != 'failure' }}
-      # - name: Upload Test Report
-      #   uses: dorny/test-reporter@v1
-      #   if: ${{ (success() || failure()) && steps.pnpm-install.conclusion != 'failure' }}
-      #   with:
-      #     name: Tests
-      #     path: artifacts/junit-*.xml
-      #     reporter: jest-junit
+      - name: Test
+        run: pnpm test
+        # run all of Build/Lint/Test even if earlier steps fail so we have "all results" at our disposal.
+        if: ${{ (success() || failure()) && steps.pnpm-install.conclusion != 'failure' }}
+      - name: Upload Test Report
+        uses: dorny/test-reporter@v1
+        if: ${{ (success() || failure()) && steps.pnpm-install.conclusion != 'failure' }}
+        with:
+          name: Tests
+          path: '**/build/junit-*.xml'
+          reporter: jest-junit
